/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.logger;

import com.example.logger.enums.Level;
import com.example.logger.enums.Target;

public interface Logger {

    void setLevel(Target target, Level level);

    void debug(String msg);

    void info(String msg);

    void warning(String msg);

    void error(String msg);

}
